// Package domain provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/deepmap/oapi-codegen/v2 version v2.1.0 DO NOT EDIT.
package domain

import (
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Availability defines model for Availability.
type Availability struct {
	Available bool    `json:"available"`
	Price     float32 `json:"price"`
}

// BookingRequest defines model for BookingRequest.
type BookingRequest struct {
	ContactDetails struct {
		Email *string `json:"email,omitempty"`
		Phone *string `json:"phone,omitempty"`
	} `json:"contactDetails"`
	CustomerName       string             `json:"customerName"`
	EndDate            openapi_types.Date `json:"endDate"`
	PaymentInformation struct {
		CardNumber *string `json:"cardNumber,omitempty"`
		Cvv        *string `json:"cvv,omitempty"`
		ExpiryDate *string `json:"expiryDate,omitempty"`
	} `json:"paymentInformation"`
	PropertyId int                `json:"propertyId"`
	StartDate  openapi_types.Date `json:"startDate"`
}

// BookingResponse defines model for BookingResponse.
type BookingResponse struct {
	BookingId           openapi_types.UUID `json:"bookingId"`
	CheckInInstructions *string            `json:"checkInInstructions,omitempty"`
	CustomerName        string             `json:"customerName"`
	EndDate             openapi_types.Date `json:"endDate"`
	PropertyId          int                `json:"propertyId"`
	StartDate           openapi_types.Date `json:"startDate"`
	TotalAmount         float32            `json:"totalAmount"`
}

// Property defines model for Property.
type Property struct {
	AccessInstructions        *string `json:"accessInstructions,omitempty"`
	Address                   string  `json:"address"`
	ArchitecturalStyle        *string `json:"architecturalStyle,omitempty"`
	Bedrooms                  int     `json:"bedrooms"`
	City                      string  `json:"city"`
	Country                   string  `json:"country"`
	EmergencyInstructions     *string `json:"emergencyInstructions,omitempty"`
	FeatureDescription        *string `json:"featureDescription,omitempty"`
	Guests                    int     `json:"guests"`
	Layout                    *string `json:"layout,omitempty"`
	Location                  string  `json:"location"`
	PropertyId                int     `json:"propertyId"`
	RecommendationDescription *string `json:"recommendationDescription,omitempty"`
	RuleDescription           *string `json:"ruleDescription,omitempty"`
	SecurityDescription       *string `json:"securityDescription,omitempty"`
	Size                      int     `json:"size"`
	Utilities                 *string `json:"utilities,omitempty"`
}

// SearchOptions defines model for SearchOptions.
type SearchOptions struct {
	Bedrooms *int    `json:"bedrooms,omitempty"`
	City     *string `json:"city,omitempty"`
	Country  *string `json:"country,omitempty"`
	Guests   *int    `json:"guests,omitempty"`
}

// GetPropertiesPropertyIdAvailabilityParams defines parameters for GetPropertiesPropertyIdAvailability.
type GetPropertiesPropertyIdAvailabilityParams struct {
	StartDate openapi_types.Date `form:"startDate" json:"startDate"`
	EndDate   openapi_types.Date `form:"endDate" json:"endDate"`
}

// PostBookingsJSONRequestBody defines body for PostBookings for application/json ContentType.
type PostBookingsJSONRequestBody = BookingRequest

// PostPropertiesSearchJSONRequestBody defines body for PostPropertiesSearch for application/json ContentType.
type PostPropertiesSearchJSONRequestBody = SearchOptions
