AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: Booking API

Globals:
  Api:
    OpenApiVersion: 3.0.3
    TracingEnabled: true
  Function:
    Timeout: 5
    MemorySize: 128
    Handler: bootstrap
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Environment:
      Variables:
        PROPERTIES_TABLE_NAME: !Ref PropertiesTable
        PROPERTIES_TABLE_ARN: !GetAtt PropertiesTable.Arn
        BOOKINGS_TABLE_NAME: !Ref BookingsTable
        BOOKINGS_TABLE_ARN: !GetAtt BookingsTable.Arn
    Tracing: Active


Parameters:
  environment:
    Type: "String"
    Default: dev


Resources:

  BookingApiGateway:
    Type: AWS::Serverless::Api
    Properties:
      Name: "booking"
      StageName: !Sub "${environment}"
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: ./api.yaml
    Connectors:
      ApiToLambdaConn:
        Properties:
          Destination:
            - Id: SearchFunction
            - Id: PropertyFunction
            - Id: AvailabilityFunction
            - Id: BookingFunction
            - Id: CancelFunction
          Permissions:
            - Write

  SearchFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: search
      CodeUri: ./cmd/functions/search/
    Connectors:
      TableConn:
        Properties:
          Destination:
            Id: PropertiesTable
          Permissions:
            - Read

  PropertyFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: property
      CodeUri: ./cmd/functions/property/
    Connectors:
      TableConn:
        Properties:
          Destination:
            - Id: PropertiesTable
          Permissions:
            - Read

  AvailabilityFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: availability
      CodeUri: ./cmd/functions/availability/
    Connectors:
      TableConn:
        Properties:
          Destination:
            - Id: PropertiesTable
            - Id: BookingsTable
          Permissions:
            - Read

  BookingFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: booking
      CodeUri: ./cmd/functions/booking/
    Connectors:
      PropertiesConn:
        Properties:
          Destination:
            - Id: PropertiesTable
          Permissions:
            - Read
      BookingsConn:
        Properties:
          Destination:
            - Id: BookingsTable
          Permissions:
            - Read
            - Write

  CancelFunction:
    Type: AWS::Serverless::Function
    Metadata:
      BuildMethod: go1.x
    Properties:
      FunctionName: cancel
      CodeUri: ./cmd/functions/cancel/
    Connectors:
      TableConn:
        Properties:
          Destination:
            - Id: BookingsTable
          Permissions:
            - Read
            - Write

  PropertiesTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Properties
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: propertyId
          AttributeType: N
        - AttributeName: city
          AttributeType: S
        - AttributeName: country
          AttributeType: S
        - AttributeName: bedrooms
          AttributeType: N
        - AttributeName: guests
          AttributeType: N
      KeySchema:
        - AttributeName: propertyId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: CityIndex
          KeySchema:
            - AttributeName: city
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: CountryIndex
          KeySchema:
            - AttributeName: country
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: BedroomsIndex
          KeySchema:
            - AttributeName: bedrooms
              KeyType: HASH
          Projection:
            ProjectionType: ALL
        - IndexName: GuestsIndex
          KeySchema:
            - AttributeName: guests
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Bookings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
        - AttributeName: propertyId
          AttributeType: N
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH
      GlobalSecondaryIndexes:
        - IndexName: PropertyIdIndex
          KeySchema:
            - AttributeName: propertyId
              KeyType: HASH
          Projection:
            ProjectionType: ALL

  ApplicationResourceGroup:
    Type: AWS::ResourceGroups::Group
    Properties:
      Name: !Sub "ApplicationInsights-SAM-${AWS::StackName}"
      ResourceQuery:
        Type: CLOUDFORMATION_STACK_1_0

  ApplicationInsightsMonitoring:
    Type: AWS::ApplicationInsights::Application
    Properties:
      ResourceGroupName: !Ref ApplicationResourceGroup
      AutoConfigurationEnabled: true

Outputs:
  ApiGatewayEndpoint:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${BookingApiGateway}.execute-api.${AWS::Region}.amazonaws.com/${environment}"
  ApiGatewayId:
    Description: "API Gateway ID"
    Value: !Sub "${BookingApiGateway}"
